kind: 'floom/pipeline/1.2'

pipeline:
  name: floom-docs-pipeline

  model:
    - package: floom/model/connector/openai
      model: gpt-3.5-turbo
      apiKey: sk-ABC123

  prompt:
      context:
        - package: floom/prompt/context/pdf
          path: /etc/myfiles/tutorial.pdf


  response:
    format:
     - package: floom/response/formatter
       type: text